langauge: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
script: "./build.sh"
sudo: required
notifications:
  email:
  - fhir-svn-travis@dilute.net

before_install:
- openssl aes-256-cbc -K $encrypted_7d142fa10e4e_key -iv $encrypted_7d142fa10e4e_iv -in deploy.build.fhir.org.enc -out ~/deploy.build.fhir.org -d
- chmod 600 ~/deploy.build.fhir.org
- mkdir ~/.aws
- openssl aes-256-cbc -K $encrypted_df9311acf27c_key -iv $encrypted_df9311acf27c_iv -in aws.config.enc -out ~/.aws/config -d
- chmod 600 ~/.aws/config
- sudo pip install awscli
- curl https://raw.githubusercontent.com/mishudark/s3-parallel-put/b091a6ec9abd684d14c1d35b1a99164a9077e3f3/s3-parallel-put > ~/s3-parallel-put
- mkdir fhir-spec
- cd fhir-spec
- wget http://hl7.org/fhir/fhir-spec.zip
- unzip -q fhir-spec.zip
- rm fhir-spec.zip
- aws s3 cp . s3://fhir-build-test --recursive
- exit 1
