langauge: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
script: "./build.sh"
sudo: required
notifications:
  email:
  - fhir-svn-travis@dilute.net
  
env:
  global:
    AWS_ACCESS_KEY_ID: AKIAI5IWFLWYKLYRUGPQ
    AWS_SECRET_ACCESS_KEY:
      secure: jQVzfDodzLWbzOKAHlXLk8D+rqZCrR1V9KxSWWTEPyuYcJIgJTROUUF5am970d2EGtTz+0vxRd9z5zZE2vjo/Qzujufwcf9fDEm1dXJQa/phGXKZENy0MTBtAIqtM59BS1IihwsXKlPqXnsZQY4Sbqm3bShUXEwPj93qYjHjS6M=


before_install:
- openssl aes-256-cbc -K $encrypted_7d142fa10e4e_key -iv $encrypted_7d142fa10e4e_iv -in deploy.build.fhir.org.enc -out ~/deploy.build.fhir.org -d
- chmod 600 ~/deploy.build.fhir.org
- sudo pip install --upgrade boto 
- curl https://raw.githubusercontent.com/mishudark/s3-parallel-put/b091a6ec9abd684d14c1d35b1a99164a9077e3f3/s3-parallel-put > ~/s3-parallel-put
- chmod +x ~/s3-parallel-put
- mkdir fhir-spec
- cd fhir-spec
- wget http://hl7.org/fhir/fhir-spec.zip
- unzip -q fhir-spec.zip
- rm fhir-spec.zip
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY | head -c 10
- ~/s3-parallel-put --bucket=fhir-build-test --host=s3.amazonaws.com --put=stupid .
- exit 1
