langauge: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
script: "./build.sh"
sudo: required
notifications:
  email:
  - fhir-svn-travis@dilute.net
  - grahame@healthintersections.com.au
  - e.kramer@furore.com
  - brian_pos@hotmail.com
  webhooks:
  - https://chat.fhir.org/api/v1/external/travis?stream=committers&topic=ci-notifications&api_key=IelOy1KhccEy3QpRIeOrtQUTqw98Kvr8
before_install:
- openssl aes-256-cbc -K $encrypted_7d142fa10e4e_key -iv $encrypted_7d142fa10e4e_iv
  -in deploy.build.fhir.org.enc -out ~/deploy.build.fhir.org -d
- chmod 600 ~/deploy.build.fhir.org
after_success:
- mkdir hl7-fhir.github.io
- cd hl7-fhir.github.io
- cp -r ../publish/* .
- cd - 
- pwd
- ls -la
env:
  global:
    secure: MV6r5LHUxQns93+NuKCv+iJPDLoSRSXpJ5YNq36mlO7pKIiHxWOYkrdxaXFyZU7lJzYMuJuFFpPPmzBNN8AqGo+3GY/ge6cODbYyAyS+PPUnazKNSyha7Hu9XQh1px44NBgnwE3wbltXYYvwQbHe8vXhDwBLXYZe9xj0g4YY4ms=
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJYYBL54CJKWOCMAQ
  secret_access_key: 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
  bucket: fhir-build-test
  local-dir: hl7-fhir.github.io
  acl: public_read
  on:
    branch: test-s3-deploy
